apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullName }}
data:
  anchor-config.yaml: |
    version: 1
    
    stellar_network:
      network: {{ .Values.stellar_network.network | default "TESTNET" }}
      {{- if eq .Values.stellar_network.network "PUBNET" }}
      network_passphrase: "Public Global Stellar Network ; September 2015"
      horizon_url: {{ .Values.stellar_network.horizon_url | default "https://horizon.stellar.org" }}
      {{- else }}
      network_passphrase: "Test SDF Network ; September 2015"
      horizon_url: {{ .Values.stellar_network.horizon_url | default "https://horizon-testnet.stellar.org" }}
      {{- end }}

    callback_api:
      {{ include "common.addField" (list "base_url" .Values.callback_api.base_url ) }}
      {{ include "common.addField" (list "auth_type" .Values.callback_api.auth_type ) }}
      {{ include "common.addMap" (list "options" .Values.callback_api.options 6 8 ) }}

    {{- if .Values.payment_observer.enabled }}
    payment_observer:
      {{ include "common.addField" (list "enabled" .Values.payment_observer.enabled ) | default "false" }}
      {{ include "common.addField" (list "circle_url" .Values.payment_observer.circle_url ) | default "https://api-sandbox.circle.com" }}
      {{ include "common.addField" (list "tracked_wallet" .Values.payment_observer.tracked_wallet ) | default "all" }}
    {{- end }}

    {{- if .Values.assets }}
    assets:
      type: json
      value: |
      {
        "assets": {{ toPrettyJson .Values.assets | indent 4 }}
      }
    {{- end }}
    
    #    data:
    #      type: ""
    #      options: ""
    #
    
    languages: en
    
    logging:
      {{ include "common.addField" (list "level" .Values.log_level ) }}
    
    metrics:
      enabled: true
      extras_enabled: true
      run_interval: ""
    
    {{- if .Values.events.enabled }}
    events:
      {{ include "common.addField" (list "enabled" .Values.events.enabled ) | default "false" }}
      {{ include "common.addField" (list "publisher_type" .Values.events.publisher_type ) }}
      options:
        {{ include "common.addField" (list "bootstrap_server" .Values.events.options.bootstrap_server ) }}
        {{ include "common.addField" (list "use_IAM" .Values.events.options.use_IAM ) }}
        {{ include "common.addField" (list "aws_region" .Values.events.options.aws_region ) }}
        {{ include "common.addField" (list "use_single_queue" .Values.events.options.use_single_queue ) }}
        # event_type_to_queue:
    {{- end }}
