apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullName }}
data:
  anchor-config.yaml: |
    version: 1
    
#    stellar_network:
#      network: {{ .Values.stellar_network.network | default "TESTNET" }}
#      {{- if eq .Values.stellar.app_config.app.stellar_network "PUBNET" }}
#        network_passphrase: "Public Global Stellar Network ; September 2015"
#        horizon_url: {{ .Values.stellar_network.horizon_url | default "https://horizon.stellar.org" }}
#      {{- else }}
#        network_passphrase: "Test SDF Network ; September 2015"
#        horizon_url: {{ .Values.stellar_network.horizon_url | default "https://horizon-testnet.stellar.org" }}
#      {{- end }}
#
#    callback_api:
#      base_url: {{ .Values.callback_api.base_url | https://api-sandbox.circle.com }}
#      auth_type: {{ .Values.callback_api.auth_type  | "NONE" }}
#      {{- if eq .Values.callback_api.auth_type "JWT_TOKEN" }}
#      options:
#        expiration_milliseconds: {{ .Values.callback_api.expiration_milliseconds | default 30000 }}
#      {{- end }}
#
#    {{- if .Values.payments_observer.enabled }}
#    payment_observer:
#      enabled: true
#      circle_url: {{ .Values.payment_observer.circle_url | default "https://api-sandbox.circle.com" }}
#      tracked_wallet: {{ .Values.payment_observer.tracked_wallet | default "all" }}
#    {{- end }}

    {{ include "test" . }}
    languages: en
    
    logging:
      level: INFO
    
    metrics:
      enabled: true
      extras_enabled: true
      run_interval: ""
    
    events:
      enabled: true
      publisher_type: ""
      options:  ""
#
#    {{- if .Values.assets }}
#    assets:
#      type: json
#      value: |
#      {
#        "assets": {{ toPrettyJson .Values.assets | indent 4 }}
#      }
#    {{- end }}
    
#    data:
#      type: ""
#      options: ""
#
#  stellar-wks.toml: |
#    ACCOUNTS = {{ .Values.stellar.toml.accounts | default "[\"GDZCLP2PHTWYQ3BWZMC5D4ZUJX5NU4S7YZHC5EBFAFKL6UJUQ5RKDGSY\"]" }}
#    VERSION = "{{ .Values.stellar.toml.version | default "0.1.0" }}"
#    NETWORK_PASSPHRASE = "{{ .Values.stellar.app_config.app.stellarNetworkPassphrase | default "Test SDF Network ; September 2015" }}"
#    SIGNING_KEY = "{{ .Values.stellar.toml.signing_key | default "GDZCLP2PHTWYQ3BWZMC5D4ZUJX5NU4S7YZHC5EBFAFKL6UJUQ5RKDGSY" }}"
#    TRANSFER_SERVER = "{{ .Values.stellar.app_config.app.hostUrl }}/sep6"
#    TRANSFER_SERVER_SEP0024 = "{{ .Values.stellar.app_config.app.hostUrl }}/sep24"
#    WEB_AUTH_ENDPOINT = "{{ .Values.stellar.app_config.app.hostUrl }}/auth"
#    KYC_SERVER = "{{ .Values.stellar.app_config.app.hostUrl }}/sep12"
#    DIRECT_PAYMENT_SERVER = "{{ .Values.stellar.app_config.app.hostUrl }}/sep31"
#    ANCHOR_QUOTE_SERVER = "{{ .Values.stellar.app_config.app.hostUrl }}/sep38"
#
#    [[CURRENCIES]]
#    {{- if ((.Values.stellar).toml).currencies }}
#    {{- range .Values.stellar.toml.currencies }}
#    code = {{ .code | quote }}
#    issuer = {{ .issuer | quote }}
#    status = {{ .status | quote }}
#    is_asset_anchored = {{ .is_asset_anchored }}
#    anchor_asset_type = {{ .anchor_asset_type }}
#    desc = {{ .desc | quote }}
#    {{- end }}
#    {{- else }}
#    code = "USDC"
#    issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
#    status = "test"
#    is_asset_anchored = true
#    anchor_asset_type = "fiat"
#    desc = "A test USDC issued by Circle."
#    {{- end }}
#
#    [DOCUMENTATION]
#    {{- if ((.Values.stellar).toml).documentation }}
#    ORG_NAME = {{ .Values.stellar.toml.documentation.ORG_NAME | default "My Organization" | quote }}
#    ORG_URL = {{ .Values.stellar.toml.documentation.ORG_URL  | default "https://www.myorg.org" | quote }}
#    ORG_DESCRIPTION = {{ .Values.stellar.toml.documentation.ORG_DESCRIPTION | default "My Organization description" | quote }}
#    ORG_LOGO = {{ .Values.stellar.toml.documentation.ORG_LOGO | default "https://myorglogo.png" | quote }}
#    ORG_SUPPORT_EMAIL = {{ .Values.stellar.toml.documentation.ORG_SUPPORT_EMAIL | default "myname@myemail.org" | quote }}
#    {{- else }}
#    ORG_NAME = "My Organization"
#    ORG_URL = "https://www.myorg.org"
#    ORG_DESCRIPTION = "Please Customize all DOCUMENTATION values for your organization"
#    ORG_LOGO = "https://myorglogo.png"
#    ORG_SUPPORT_EMAIL="myname@myemail.org"
#    {{- end }}